name: reusable-workflow
on:
  push:
    branches: 
      - main
    paths: 
      - "Backend/**"
  workflow_dispatch: 
  workflow_call: 
    inputs:
      name-a:
        type: string
        required: true 
jobs:
  Build_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [19,20]
    steps:
      - name: git checkout
        uses: actions/checkout@v7
      - name: installing node
        uses: actions/setup-node@v7
        with:
          node-version: ${{matrix.version}}
      - name: Installing Dependencies
        run: npm ci
  Deploy_job:
    uses: owner/GitHub-actions/.github/workflows/CD.yml@main
    
          
          
