name: reusable-workflow
on:
  workflow_dispatch: 
  workflow_call: 
    inputs:
      version:
        type: string
        required: true
jobs:
  Build_job:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v7
      - name: installing node
        uses: actions/setup-node@v7
        with:
          node-version: ${{inputs.version}}
      - name: Installing Dependencies
        run: npm install
 
    
          
          
