name: sample jobs:
on:
  push:
    branches:
      - main
    workflow_dispatch:
jobs:
  Build_Job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "first step"
  Deploy_job:
    uses: ./.github/workflows/resuable-workflow.yml
    with:
      node-version: 20
    needs: Build_Job
      
